#!/usr/bin/env python3
"""Generate the headline facts sheet for #306 from a served QA store.

Reads the running no-fetch app through the production API — the findings
projection for every window preset the Diagnose workstation offers plus the
whole-day read, and for each row the evidence endpoint its chart reads — and
writes one CSV row per findings row carrying every fact the engine publishes
for it. The operator writes an example headline against each row; the
templates recorded under ``## Headline templates`` in ``design.md`` are built
from those examples and may name only the columns this sheet marks as slots.

Columns prefixed ``ref_`` are reference-only: they come from the Finding case
file, which the projection cannot read (it needs a store), so they can inform
a sentence but never be a template slot.

Every source is a synthetic QA store served through the declared
copy-then-serve command (``AGENTS.md`` "The data boundary"); the showcase
alone does not publish every family-and-register pair, so named QA case
stores are passed as extra sources.

    uv run python openspec/changes/left-column-pattern/evidence/headline-facts.py \\
        --source showcase=http://127.0.0.1:8306 \\
        --source basal-insufficient-seven-night=http://127.0.0.1:8311

stdlib only; no token is sent because the declared serve runs with ``--token ''``.
"""

from __future__ import annotations

import argparse
import csv
import json
import re
import sys
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[3]
WORKSTATION = ROOT / "frontend" / "diagnose-workstation.js"
DEFAULT_OUT = HERE / "headline-facts.csv"
BASAL_SLOT_MINUTES = 30

GENERATED_BY = "openspec/changes/left-column-pattern/evidence/headline-facts.py"
NOTE = ("synthetic — every row is read from a served QA store generated by "
        "scripts/gen_qa_e2e_db.py; no patient data. Columns prefixed ref_ are "
        "reference-only (Finding case file) and are never template slots.")

ROW_KEYS = (
    "id", "register", "kind", "title", "priority", "tier", "parameter", "label",
    "span", "direction", "asserts_move", "lean", "current", "recommended",
    "estimate", "support", "reason", "annotation", "members", "lever",
    "appearances", "episodes", "evidence", "verdict_counts",
    "verdict_counts_by_family", "chips", "window_scope", "past_setting",
    "programmed_now", "regime_end", "run_ids", "event_chart",
)
EVIDENCE_KEYS = (
    "ev_family",
    # basal night evidence
    "ev_roster_count", "ev_directional_support_count", "ev_excluded_night_count",
    "ev_roster_glucose_mean", "ev_safety_status", "ev_current", "ev_recommended",
    "ev_estimate",
    # ISF rest-window evidence
    "ev_detected_windows", "ev_qualifying_windows", "ev_qualifying_steps",
    "ev_direction",
    # I:C block evidence (published counts)
    "ev_block_state", "ev_support", "ev_effective_support", "ev_examined_runs",
    "ev_excluded_runs",
)
REFERENCE_KEYS = (
    "ref_claimed", "ref_denominator", "ref_noun", "ref_verdict_counts",
    "ref_event_anchor", "ref_event_counts", "ref_comparison",
)
COLUMNS = ("source", "window_key", "window_label", "start_min", "end_min",
           *ROW_KEYS, *EVIDENCE_KEYS, *REFERENCE_KEYS)


def window_presets() -> list[tuple[str, str, int | None, int | None]]:
    """The presets the workstation offers, read from its own ``WINDOWS`` table."""
    source = WORKSTATION.read_text(encoding="utf-8")
    block = re.search(r"const WINDOWS = \{(.*?)\n\};", source, re.S)
    if block is None:
        sys.exit(f"WINDOWS table not found in {WORKSTATION}")
    presets = []
    for key, label, start, end in re.findall(
            r"(\w+): \{ label: '([^']+)', range: \[(\d+), (\d+)\] \}", block.group(1)):
        start, end = int(start), int(end)
        if (start, end) == (0, 1440):
            presets.append((key, label, None, None))  # the whole-day read
        else:
            presets.append((key, label, start, end))
    if not presets:
        sys.exit("WINDOWS table parsed to nothing")
    return presets


def get(base: str, path: str, **params):
    query = urllib.parse.urlencode({k: v for k, v in params.items() if v is not None})
    url = f"{base}{path}" + (f"?{query}" if query else "")
    try:
        with urllib.request.urlopen(url, timeout=60) as response:
            return json.load(response)
    except urllib.error.HTTPError as error:
        body = error.read().decode("utf-8", "replace")
        sys.exit(f"{url} -> {error.code}: {body}")


def cell(value):
    if value is None:
        return ""
    if isinstance(value, (dict, list)):
        return json.dumps(value, sort_keys=True)
    return value


def evidence_for(base: str, row: dict, generation: str) -> dict:
    """The tile counts the row's own chart reads, keyed by family."""
    parameter, register = row.get("parameter"), row.get("register")
    if parameter == "basal_rate" and register in ("assert", "held", "blind"):
        slot = row["span"]["start_min"] // BASAL_SLOT_MINUTES
        ev = get(base, "/api/diagnose/basal-night-evidence", slot=slot)
        return {
            "ev_family": "basal_night_evidence",
            "ev_roster_count": ev["roster_count"],
            "ev_directional_support_count": ev["directional_support_count"],
            "ev_excluded_night_count": ev["excluded_night_count"],
            "ev_roster_glucose_mean": ev["roster_glucose_mean"],
            "ev_safety_status": ev["safety_status"],
            "ev_current": ev["current"], "ev_recommended": ev["recommended"],
            "ev_estimate": ev["estimate"],
        }
    if parameter == "isf":
        ev = get(base, "/api/diagnose/isf-rest-window-evidence")
        return {"ev_family": "isf_rest_window_evidence",
                **{f"ev_{k}": v for k, v in ev["counts"].items()},
                "ev_direction": ev["finding"]["direction"]}
    if parameter == "carb_ratio" and register in ("assert", "held"):
        ev = get(base, "/api/diagnose/carb-ratio-block-evidence",
                 block_id=row["id"].split(":", 1)[1], analysis_generation=generation)
        block = ev["block"]
        return {"ev_family": "ic_block_counts", "ev_block_state": block["state"],
                "ev_support": block["support"],
                "ev_effective_support": block["effective_support"],
                "ev_examined_runs": block["examined_runs"],
                "ev_excluded_runs": block["excluded_runs"]}
    return {}


def reference_for(base: str, row: dict, preparation: dict | None) -> dict:
    """Finding case-file facts: reference-only, never a slot."""
    if row.get("register") != "finding" or preparation is None:
        return {}
    header = preparation["behavioral_case_headers"].get(row["id"])
    if header is None:
        return {"ref_noun": "withheld"}
    case = get(base, "/api/diagnose/finding-case-file",
               projection_id=preparation["projection_id"], finding_id=row["id"],
               alignment="event")
    projection = case["projection"]
    return {
        "ref_claimed": header["summary"]["claimed"],
        "ref_denominator": header["summary"]["denominator"],
        "ref_noun": header["summary"]["noun"],
        "ref_verdict_counts": header["verdict_counts"],
        "ref_event_anchor": (projection.get("anchor") or {}).get("label"),
        "ref_event_counts": projection.get("counts"),
        "ref_comparison": projection.get("comparison"),
    }


def rows_for(label: str, base: str) -> list[dict]:
    out = []
    for key, window_label, start, end in window_presets():
        findings = get(base, "/api/diagnose/findings", start_min=start, end_min=end)
        generation = findings["analysis_generation"]
        preparation = get(base, "/api/diagnose/finding-case-file-preparation",
                          start_min=start, end_min=end) if any(
            r.get("register") == "finding" for r in findings["rows"]) else None
        for row in findings["rows"]:
            record = {"source": label, "window_key": key, "window_label": window_label,
                      "start_min": start, "end_min": end}
            record.update({k: row.get(k) for k in ROW_KEYS})
            record.update(evidence_for(base, row, generation))
            record.update(reference_for(base, row, preparation))
            out.append(record)
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--source", action="append", metavar="LABEL=URL",
                        help="a served QA store; repeatable (default showcase=http://127.0.0.1:8306)")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()
    sources = [s.split("=", 1) for s in (args.source or ["showcase=http://127.0.0.1:8306"])]
    records = [record for label, base in sources for record in rows_for(label, base.rstrip("/"))]
    with args.out.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(["_generated_by", GENERATED_BY])
        writer.writerow(["_note", NOTE])
        writer.writerow(COLUMNS)
        for record in records:
            writer.writerow([cell(record.get(column)) for column in COLUMNS])
    print(f"wrote {args.out} ({len(records)} rows from {len(sources)} sources)")


if __name__ == "__main__":
    main()
