#!/usr/bin/env python3
"""Generate synthetic design inputs and the current app material for #348."""
from __future__ import annotations
import argparse
import json
from pathlib import Path
import sys
import tempfile
ROOT = Path(__file__).resolve().parents[2]
sys.path[:0] = [str(ROOT), str(ROOT / "scripts")]
from ciq_autotune.store import Store
from ciq_autotune.analyzers.scenario import build_scenarios
from gen_qa_e2e_db import generate
from qa_e2e_cases import QA_CASES

def outputs():
    html = (ROOT / "frontend/index.html").read_text()
    material = html.split("\n  <style>\n", 1)[1].split("    /* #634: #app", 1)[0]
    css = "/* GENERATED by mockups/harmonic-v2.exploration/generate.py. Sources: frontend/index.html, frontend/shell.css, frontend/theme.css. */\n"
    css += (ROOT / "frontend/shell.css").read_text() + "\n" + material + "\n" + (ROOT / "frontend/theme.css").read_text()
    case = next(c for c in QA_CASES if c.name == "behavioral-late-bolus")
    with tempfile.TemporaryDirectory(prefix="harmonic-v2-fixture-") as scratch:
        path = Path(scratch) / "case.sqlite"
        generate(path, case)
        with Store.open_readonly(str(path)) as store:
            scenarios = build_scenarios(store).to_dict()
    data = {"_generated_by": "mockups/harmonic-v2.exploration/generate.py", "_note": "SYNTHETIC. Manufactured QA case; no real records. Proposed priority selection is illustrative, not a shipped backend verdict.", "case": case.name, "scenarios": scenarios}
    return {ROOT / "mockups/_theme-app.css": css, ROOT / "mockups/harmonic-v2.exploration/evidence.json": json.dumps(data, indent=2, sort_keys=True) + "\n"}

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    failed = []
    for path, content in outputs().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                failed.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(content)
    if failed:
        print("harmonic-v2 design: stale " + ", ".join(failed))
        return 1
    print("harmonic-v2 design: current" if args.check else "harmonic-v2 design: generated")
    return 0
if __name__ == "__main__":
    raise SystemExit(main())
