// GENERATED by mockups/harmonic-v2.exploration/generate.py from frontend/index.html:3757.
export const glossaryGroups = [
          { title: 'Basal', terms: [
            { term: 'Basal rate', unit: 'U/h', def: 'The continuous background insulin Control-IQ delivers between meals and corrections.' },
            { term: 'Programmed basal', unit: 'U/h', def: "The rate set in your pump's profile for a given time of day." },
            { term: 'Delivered basal', unit: 'U/h', def: 'What Control-IQ actually delivered, which can differ from the programmed rate when the algorithm adjusts up, down, or suspends.' },
            { term: 'Clean window', def: "A stretch of time used as evidence because it wasn't disturbed by a recent bolus, meal, or algorithm correction — so the delivered basal reflects the profile setting, not a reaction to something else." },
          ] },
          { title: 'ISF', terms: [
            { term: 'ISF', unit: 'mg/dL per U — Insulin Sensitivity Factor', def: 'How much one unit of insulin is expected to lower blood glucose. A lower number means more insulin is needed to correct the same rise.' },
            { term: 'Wide CI', def: "A confidence interval (see CI below) wide enough that the estimate is uncertain — flagged so you know to weight it less." },
          ] },
          { title: 'I:C', terms: [
            { term: 'I:C', unit: 'g/U — Insulin-to-Carb ratio', def: 'How many grams of carbohydrate one unit of insulin covers. A lower number means more insulin is needed per gram of carbs.' },
          ] },
          { title: 'General', terms: [
            { term: 'CI', def: 'Confidence interval — the range an estimate is likely to fall within given the data available. Narrower means more reliable.' },
            { term: 'Epoch', def: 'A stretch over which a pump setting appears unchanged. Basal setting epochs can narrow basal measurement windows; ISF/I:C measurements use the full requested window and keep setting epochs as caveats/settling context.' },
            { term: 'CGM', def: 'Continuous Glucose Monitor — the sensor providing the glucose readings shown throughout this app.' },
            { term: 'Bolus', unit: 'U', def: 'A single dose of insulin given for a meal or to correct a high, as opposed to the continuous basal rate.' },
            { term: 'IOB', def: 'Insulin On Board — insulin already delivered that is still active in the body.' },
          ] },
];
